name: Auto Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天自动运行
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync Upstream
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 这一行使用 GitHub 官方命令行工具直接同步，把里面的 main 改成你和原作者的分支名即可
          gh repo sync ${{ github.repository }} -b main
